# Generated by Django 3.2.9 on 2021-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(null=True)),
                ('datetime_turn', models.DateTimeField()),
                ('parts_quantity', models.IntegerField()),
                ('area_production', models.FloatField()),
                ('line_stops', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producao',
                'verbose_name_plural': 'Producoes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Quantity',
                'verbose_name_plural': 'Quantities',
                'ordering': ['-inicio'],
            },
        ),
    ]
