# Generated by Django 3.2.9 on 2021-11-21 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='producao',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='producao.producao'),
            preserve_default=False,
        ),
    ]
