# Generated by Django 3.2.9 on 2021-11-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20211121_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='resultado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
