# Generated by Django 3.2.11 on 2022-01-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_paradasproducao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paradasproducao',
            options={'verbose_name': 'parada_producao', 'verbose_name_plural': 'parada_producao'},
        ),
        migrations.AlterModelTable(
            name='paradasproducao',
            table='parada_producao',
        ),
    ]
