# Generated by Django 3.2.9 on 2021-11-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_alter_quantity_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='resultado',
        ),
    ]
