# Generated by Django 3.2.11 on 2022-01-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_auto_20220123_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasproducao',
            old_name='message',
            new_name='mensagem',
        ),
    ]
