apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: 192.168.0.2:5432
    access: proxy
    password: postgres
    user: postgres
    database: postgres
    basicAuth: false
    isDefault: true
    jsonData:
      sslmode: disable
    version: 1
    editable: true
